### ISSUE TITLE
Info to Upload File

### ISSUE THREAD

**Issue by enricogaggero** [viniciussanchez/RESTRequest4Delphi#100]
Thanks for share your interesting component.
I'm study regarding to upload file funcionality usind AddFile(), I'have made a rest server than run correctly with Indy tIdHTTP but I have problem with your component.
I add my example code below, please can you tell me if there are some errors in my code?
I think is a good idea to add to sample code a upload and download example in a future release.
Another question ... have you planned to put a debug function to know what is sent to server ?  
Regards
Enrico

procedure Tfmmain.ButtonUploadClick(Sender: TObject);
var
  LResponse: IResponse;
  FStreamFile: TFileStream;
  Response: string;
begin

    FStreamFile := TFileStream.Create(GetCurrentDir + '\files\Test_PDF.pdf', fmOpenRead);

    LResponse := TRequest.New.BaseURL
//      (BASE_URL + 'files/uploadfile.php').TokenBearer(JWTToken) // normal 
      (BASE_URL + 'imageput').TokenBearer(JWTToken) // rewriteurl
      .UserAgent('Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36')
      .AddFile('TestPDF.pdf', FStreamFile)
      .Post;

    FStreamFile.Free;
 
end;

**Comment by trainneEg7** [comment]
Olá, tambem estou com o mesmo problema.

**Comment by mauriciovictor** [comment]
conseguiu resolver?
