### ISSUE TITLE
Retorno no MacOS

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciussanchez/RESTRequest4Delphi#113]
Estou fazendo uma requisição HTTPS e no Windows e Android está vindo a resposta normalmente mas quando compilo para MacOs a resposta chega em branco, alguém já passou por isso?

**Comment by viniciussanchez** [comment]
Até o momento não tive problemas, se achar algum motivo ou solução, publique aqui por favor

**Comment by rennesgyn** [comment]
Boa noite, estou iniciando o teste com o RESTRequest4D com o Delphi XE7. Na funcionalidade do DataSetAdapter to passando um FDMemTable e ocorre varios erros de "Conversion from TJSONNumber to Pointer not supported". Vc ja possou por isso? Alguma dica?

**Comment by viniciussanchez** [comment]
Não, mas posta aqui seu JSON. Você está deixando os fields serem criados de forma automática? Ou os fields já estão adicionados no DataSet?

**Comment by rennesgyn** [comment]
> Não, mas posta aqui seu JSON. Você está deixando os fields serem criados de forma automática? Ou os fields já estão adicionados no DataSet?

[{"id":1355,"cpf":"76679772168","ie":null,"raz":"A SANDUICHERIA","fan":"A SANDUICHERIA","tel":"62993821331","cel":null,"logr":"RUA IPE ","num":"00","compl":"QD.12 LT.24","bai":"RESIDENCIAL FLOR DOS IPES","cidNom":"SENADOR CANEDO","cidUf":"GO","cep":null,"lat":null,"long":null,"precId":1,"vendId":1220,"undExt":"","appKey":"f3dea5de-fc99-4f76-a72b-f87edeb85717","ativ":false}]

esse é o exemplo do Json. Eu fiz o teste deixando os fields ser criados automaticamente e tambem adicionando, as duas formas aparesentou a mesma exceção.

**Comment by viniciussanchez** [comment]
Se alguém tiver a versão do Delphi em questão e quiser colaborar com o projeto enviando a correção, será bem vinda. Por hora, por falta de iteração e também por não ter como testar, vou fechar essa issue.

**Comment by diogenes-junior** [comment]
Tive o mesmo erro que o @rennesgyn. Consegui resolver utilizando o DatasetConverter4D (https://github.com/ezequieljuliano/DataSetConverter4Delphi) para converter para o dataset. Utilizo a versão XE7
