### ISSUE TITLE
Bug com Node

### ISSUE THREAD

**Issue by giulianon** [viniciussanchez/RESTRequest4Delphi#121]
Usando o RESTRequest compilado com a diretiva RR4D_SYNAPSE e fazendo post em um servidor node o body vai vazio.

Mesmo configurando o Accept ou Content-Type.

Pra enviar corretamente tem que setar o  mime type no FHTTPSend.

**FHTTPSend.MimeType := 'application/json';**

Acredito que o ideal seria criar TRequest.New.MimeType(''application/json'').

**Comment by viniciussanchez** [comment]
Legal... se quiser criar e enviar um pull request. Será bem vindo...

**Comment by giulianon** [comment]
Feito.
