### ISSUE TITLE
Deploy no Android

### ISSUE THREAD

**Issue by ti-muller** [viniciussanchez/RESTRequest4Delphi#126]
boa tarde Vinícius

Estou testando a biblioteca, porém quando faço os teste executando pelo Delphi tudo ok, porém ao fazer o deploy no celular a aplicação não encontra o endpoint retorno erro 404.

LResponse := TRequest.New.BaseURL(DMConexao.vsHost_App + '/usuarios/login/')
                 .AddUrlSegment('login', Edit_Usuario.Text)  // Path Variables
                 .TokenBearer(DMConexao.Get_Token)
                 .ContentType('application/json')
                 .AddBody(json.ToJSON)
                 .DataSetAdapter(MemTable_1)
                 .Accept('application/json')
                 .Get;

**Comment by viniciussanchez** [comment]
Imagino que seja porque você está passando um Body no GET. Algumas versões do Delphi bloqueia isso. E não é o correto mesmo, embora seja possível. Experimente trocar para o POST (terá que ajustar a API também), ou então usar a diretiva de compilação do INDY por exemplo, RR4D_INDY.
