### ISSUE TITLE
Requisição retorna erro de segurança quando o exe é Release

### ISSUE THREAD

**Issue by jorgecostadev** [viniciussanchez/RESTRequest4Delphi#127]
Boa tarde, Vinícius.

Comecei a ter um erro de segurança em um sistema que faz requisições REST e quebrei muita cabeça até encontrar o que poderia estar acontecendo. 
A princípio, achei que pudesse ser por causa da versão do windows do cliente, Windows 7, mas depois de muitos testes verifiquei que quando enviava um executável em Release, o erro de segurança acontecia, já quando o rodava o mesmo executável Debug este erro não acontecia.
Em outras versões do Windows o problema não acontece, independente do executável ser Debug ou Release.

Na requisição é passado um header com {'Authorization':'Basic_....'}

Você saberia me dizer o motivo de isso acontecer?

**Comment by viniciussanchez** [comment]
Como está fazendo?

**Comment by jorgecostadev** [comment]
Como forma de identificar o possível problema, acabei testando, também, com os componentes nativos e mesmo com eles o erro permanece.

Estou fazendo dessa forma:

```pascal
  RestRequest              := TRESTRequest.Create(nil);
  RestClient               := TRestClient.Create(nil);

  RestClient.BaseUrl       := aBaseURL;
  RestClient.ContentType   := 'application/json';
  RestClient.AcceptCharset := 'utf-8';

  RestRequest.Client       := RestClient;
  RestRequest.Method       := rmGET;
  RestRequest.Resource     := aResource;
  RestRequest.Params.AddHeader(aHeaderName, aHeaderValue);
  RestRequest.Execute;

  MemoResponse.Lines.Add(RestRequest.Response.Content);
```

**Comment by viniciussanchez** [comment]
e qual seria exatamente o erro?

**Comment by jorgecostadev** [comment]
Dá **erro de autorizacao**
Acredito que o header não está indo na requisição.

**Comment by viniciussanchez** [comment]
Printa o erro ai pra gente ver
