### ISSUE TITLE
RR4D_NETHTTP retornando Status Code 0 enquanto obtenho 500 no Insomnia

### ISSUE THREAD

**Issue by IagooCesaar** [viniciussanchez/RESTRequest4Delphi#135]
Caso de um erro que levanto através de um controle de Exceção do Horse com Status Code 500, 503, etc.

No insomnia recebo Status Code 500 (esperado)
Com o motor NetHTTP recebo Status Code 0

**Comment by IagooCesaar** [comment]
Percebi que ocorre "antes de chegar na API". É intermitente.
Pode ser algum barramento no Firewall ou qualquer outro componente da rede, até mesmo do protocolo TCP.

Resolvi implementando o `.Retry()` da própria biblioteca.

**Comment by viniciussanchez** [comment]
Obrigado pelo feedback
