### ISSUE TITLE
Implementar métodos para recuperar cookies

### ISSUE THREAD

**Issue by pancary** [viniciussanchez/RESTRequest4Delphi#137]
Precisamos recuperar o cookies retornado de uma requisição, pois o mesmo pode ser um token para uso na API.

Exemplo como é feito no Indy:

 FCookieName := FIdHTTP.CookieManager.CookieCollection.Cookies[0].CookieName;
 FCookieText    := FIdHTTP.CookieManager.CookieCollection.Cookies[0].CookieText;

**Comment by viniciussanchez** [comment]
Está sendo implementado o GetCookie no IResponse
