### ISSUE TITLE
Compiling problem with Interface

### ISSUE THREAD

**Issue by rickyarzu** [viniciussanchez/RESTRequest4Delphi#139]
When Compiling Smaple from NetHTTP I obtain this errore about Interface implementation and another on Async
[dcc32 Error] RESTRequest4D.Request.NetHTTP.pas(10): E2291 Missing implementation of interface method IRequest.AddFile

**Comment by viniciussanchez** [comment]
What example? I compiled [this ](https://github.com/viniciussanchez/RESTREquest4Delphi/tree/master/samples/client/delphi) example now and it worked, as shown in the image:

![image](https://github.com/viniciussanchez/RESTRequest4Delphi/assets/16382981/513e5c6d-a96f-40a7-bd12-9a1c07c1f1ed)
