### ISSUE TITLE
Transferring a file via API to a website

### ISSUE THREAD

**Issue by Fignar** [viniciussanchez/RESTRequest4Delphi#140]
using your component
I'm trying to upload a file to the site using the API
Gives an error on POST
Don't tell me what I'm doing wrong

**var
  LResponse  : IResponse;
  X          : ISuperObject;
  FStream    : TMemoryStream;
  FileName   : string;
begin
  FileName:='D:\test.xml ';
  FStream:=TMemoryStream.Create;
  FStream.LoadFile(FileName);
  LResponse:=TRequest.New.BaseURL(sURL)
    .Accept('application/json')
    .ContentType('multipart/form-data')
    .AddHeader('Authorization',sToken)
    // .AddParam('file',FileName, TRESTRequestParameterKind.pkFILE)
    .AddFile('file',FStream)
    .Post;
  X:=SO(LResponse.Content);**

----------------------
_{
 "request_content_length": 2093,
 "request_post_start": "",
 "request_method": "POST",
 "exception": "boundary missed for Content-Type: multipart/form-data",
 "request_read_bytes_start": "b'---------Embt-Boundary--2A48963E66D72938\\r\\nContent-Disposition: form-data; name=\"file\"; filename=\"file\"\\r\\nContent-Type: application/octet-stream\\r",
 "details": "Помилка з параметром boundary у запиті",
 "reason": "Невірно введені дані",
 "request_content_type": "multipart/form-data",
 "request_stream_cursor": "2093",
 "request_post_end": "",
 "can_read_body": true,
 "code": 1001,
 "request_stream_buffer": "deque([])",
 "request_read_bytes_end": " 60\\xd0\\xb3 \\xd1\\x8524</DESCRIPTION>\\r\\n</CHARACTERISTIC>\\r\\n</POSITION>\\r\\n</HEAD>\\r\\n</ORDER>\\r\\n\\r\\n---------Embt-Boundary--2A48963E66D72938--\\r\\n'",
 "request_stream_size": "0"
}_

**Comment by viniciussanchez** [comment]
What's wrong?
