### ISSUE TITLE
Autenticação OAuth2

### ISSUE THREAD

**Issue by a86r3** [viniciussanchez/RESTRequest4Delphi#149]
Boa tarde, é possível fazer pelo RestRequest4Delphi com SSL:

Para a utilização do Pix é necessário que o cliente e o servidor se comuniquem em uma conexão verificada um com o outro. A verificação é feita pelo certificado bidirecional (.PEM ou .P12), isto é, o servidor e o cliente implementaram um certificado de chave privada e um certificado de chave pública que permite que um possa assegurar-se da identidade do outro.

Por isso para fazer qualquer requisição HTTP à API Pix, incluindo a requisição de autorização junto ao OAuth2, é necessário que o certificado .P12, ou .PEM, esteja presente nos cabeçalhos da requisição.

**Se sim! teria uma exemplo ou uma dica?**

**Comment by viniciussanchez** [comment]
Sim, se estiver usando o componente atualizado e usar a engine do Indy (RR4D_INDY), terá acesso a novas propriedades para passar o certificado digital: 
![image](https://github.com/viniciussanchez/RESTRequest4Delphi/assets/16382981/d3044691-2802-4403-9678-13f4e678854d)

**Comment by antoniopdcruzbr** [comment]
Bom dia . Como  usar a engine do Indy (RR4D_INDY) . Rad 11

**Comment by antoniopdcruzbr** [comment]
Bom dia . Sei que o post é antigo. Eu usei {$DEFINE RR4D_INDY} no RESTRequest4D.Request.Contract para ter acesso as funções CertFile e KeyFile porem quando compilo dá erro no RESTRequest4D.Request.Client em type
  TRequestClient = class(TInterfacedObject, IRequest).
