### ISSUE TITLE
Campo Blob Binary

### ISSUE THREAD

**Issue by lassistemas** [viniciussanchez/RESTRequest4Delphi#150]
Tenho um campo blob binary que armazeno a foto,  quando faço um GET com opção de serializar o dataset, acontece dos situações:
1 - Quando o GET retorna mais de um registro, o campo vem como base64, sendo que em alguns caso é gravado no campo apenas parte do base64;
2-  Quando o GET retorna apenas um registro, o campo vem como o código binário da imagem.

Obs: no response sempre vem em base64 completa sem corte.

**Comment by viniciussanchez** [comment]
Bom dia... verifique se seus projetos estão atualizados. Se o erro persistir, crie um modelo para que possamos testar ou se possível, nos envie um pull request com a correção necessária para ser avaliada. Isso pode acontecer por inúmeras variáveis, como por exemplo, se o sistema estiver criando os fields no seu DataSet de forma automática ou você já tem os fields adicionados? Por isso um projeto de exemplo seria bem útil na identificação do problema.
