### ISSUE TITLE
Portabilidade do projeto da pasta "sample" para lazarus.

### ISSUE THREAD

**Issue by elvisbayerl** [viniciussanchez/RESTRequest4Delphi#151]
Fiz a portabilidade do projeto da pasta "sample" para lazarus, foi criado duas pastas: "delphi" e "lazarus".

**Comment by elvisbayerl** [comment]
Fiz a portabilidade do projeto da pasta "sample" para lazarus, foi criado duas pastas: "delphi" e "lazarus".

**Comment by viniciussanchez** [comment]
Manda o pull request por favor
