### ISSUE TITLE
FRESTRequest.Timeout; deprecated

### ISSUE THREAD

**Issue by edmjunio** [viniciussanchez/RESTRequest4Delphi#159]
**Unit** 
RESTRequest4D.Request.Client.pas (Linha 435)
**Função**
function TRequestClient.Timeout: Integer;
begin
  Result := FRESTRequest.Timeout;
end;
Propriedade Timeout descontinuada utilize  ConnectTimeout ou ReadTimeout

**Comment by viniciussanchez** [comment]
Thanks
