### ISSUE TITLE
Função ClearHeaders gerando exceção de out of range

### ISSUE THREAD

**Issue by edmjunio** [viniciussanchez/RESTRequest4Delphi#160]
Unit: RESTRequest4D.Request.NetHTTP.pas;
função ClearHeaders (Linha: 340 v4.0.4 ) Apresentando erro: out of range

Sugestão de correção:
function TRequestNetHTTP.ClearHeaders: IRequest;
{$IF COMPILERVERSION >= 34}
var
  LURLHeaders:TNetHeader;
{$ENDIF}
begin
  Result := Self;
  {$IF COMPILERVERSION >= 34}
    for LURLHeaders in FNetHTTPClient.CustHeaders do
    begin
      FNetHTTPClient.CustHeaders.Delete(LURLHeaders.Name);
    end;
  {$ELSE}
    {TODO -oAll -cCustom Headers : Clear headers with NetHTTPClient in versions below of 10.4 Sydney}
  {$ENDIF}	
end;

**Comment by viniciussanchez** [comment]
Obrigado
