### ISSUE TITLE
Fix timeout: quebra compatibilidade com Delphi RIO (10.3)

### ISSUE THREAD

**Issue by MarcosFincotto** [viniciussanchez/RESTRequest4Delphi#162]
A fix feita para adicionar o ConnectTimeout quebra a compatibilidade com o Delphi 10.3 (acredito que anterior a ele), pois a classe standart (REST.Client.TRESTRequest) ainda não tem a property ConnectTimeout, somente Timeout.

![image](https://github.com/viniciussanchez/RESTRequest4Delphi/assets/65043045/c4b892c5-5daa-432e-aaff-23b5273256d6)

**Comment by MarcosFincotto** [comment]
Vinícius, bom dia tudo bem? Que chato fechar a issue sem sequer uma troca de ideia, soa até arrogante, o que sei que você não é.
A ideia não é contribuir para sempre evoluir o projeto? Se eu estiver errado, me desculpe.

**Comment by viniciussanchez** [comment]
@MarcosFincotto me desculpa, eu acabei de aceitar um pull request com a correção do problema e liberei a versão... não respondi nada aqui porque até achei que era você que tinha enviado... atualiza para a ultima versão que já vai estar certinho... foi mal

**Comment by MarcosFincotto** [comment]
Que isso @viniciussanchez, você é um cara sensacional e de extrema importância para nossa comunidade! Um abraço e tenha uma ótima semana.

**Comment by viniciussanchez** [comment]
Obrigado, pra você também...
