### ISSUE TITLE
Lentidão na request

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciussanchez/RESTRequest4Delphi#165]
Boa tarde, estou recebendo essa mensagem para todas as requisições. e está demorando muito o retorno, independente das api. testamos até mesmo com api do google

TrafficStats	tagSocket(170) with statsTag=0xffffffff, statsUid=-1

Alguém já passou por isso? Pode me ajudar

**Comment by viniciussanchez** [comment]
Bom dia... nunca vi esse problema e também não vi ninguém reportando algo semelhante. Será que não está tendo algum bloqueio na sua rede?

**Comment by viniciussanchez** [comment]
![image](https://github.com/viniciussanchez/RESTRequest4Delphi/assets/16382981/1d49e94d-b5f7-48a8-9d6f-277f38e28fc8)

**Comment by viniciussanchez** [comment]
Achou alguma coisa?
