### ISSUE TITLE
.Adapters(TDataSetSerializeAdapter.New(memStatusAno))

### ISSUE THREAD

**Issue by caalpone** [viniciussanchez/RESTRequest4Delphi#167]
Estou recebendo este erro

![image](https://github.com/viniciussanchez/RESTRequest4Delphi/assets/6660949/416080a8-0220-460e-9b3c-555844dbdf51)

no endpoint esta vindo esta imagem abaixo

![image](https://github.com/viniciussanchez/RESTRequest4Delphi/assets/6660949/713604e7-d7f1-49b7-a308-b1082f1b791c)

quando vai exceutar o .Adapters(TDataSetSerializeAdapter.New(memStatusAno)) da o erro informado primeiro, alguem poderia me ajudar?

**Comment by viniciussanchez** [comment]
O field está criado no seu dataset? Acho que se voce criar um field Integer nele vai resolver
