### ISSUE TITLE
Envio de Stream via Android

### ISSUE THREAD

**Issue by CristianoDuarteRS** [viniciussanchez/RESTRequest4Delphi#190]
Tudo bem! Estou utilizando o RESTRequest4Delphi para enviar um arquivo em Stream para um servidor Horse, quando executo em Windows funciona perfeitamente, mas quando executo em Android, o comando nem chega ao servidor, ocorre o erro "Method Not Allowed". Tem algo de diferente que deve ser feito para compilar para Android? Obrigado!

O código do Client.

procedure EnviarArquivo(PArquivo: string);
var
  cStream: TMemoryStream;
  Req: IRequest;
  Resp: IResponse;
begin
  Req  := TRequest.New;
  CarregaHorseService(Req);

  cStream := TMemoryStream.Create;
  try
    cStream.LoadFromFile(PArquivo);
    Resp := Req.Resource('/CarregaArquivo')
               .ContentType('application/multiform-data')
               .AddFile('stream', cStream)
               .Get;
  finally
    cStream.Free;
  end;

  if Resp.StatusCode <> 200 then
    raise Exception.Create(Resp.Content);
end;

**Comment by viniciussanchez** [comment]
Boa tarde... o componente nativo do Delphi, o RESTClient, não permite passar body / arquivos em requisições GET em algumas plataformas. Se você seguir as especificações e boas práticas, não se deve de fato passar body em requisições GET. Mas o protocolo HTTP não trava isso, então cada biblioteca trabalha de uma forma.
Para contornar isso no RESTRequest4Delphi, você pode mudar o motor, e passar a usar o NetHTTP ou Indy no Android. Bastando adicionar a diretiva de compilação na sua aplicação: RR4D_INDY ou RR4D_NETHTTP, por exemplo. Depois dar um clear e build no projeto. Deve resolver.

**Comment by CristianoDuarteRS** [comment]
Tentei compilar com a diretiva RR4D_NETHTTP, mas me retornou o erro  da imagem.

![image](https://github.com/viniciussanchez/RESTRequest4Delphi/assets/86272601/356cdb88-1b7c-4729-af32-5e497b4531cf)

**Comment by viniciussanchez** [comment]
Provavelmente na sua versão do Delphi não tem essa propriedade ainda. Tenta comentar ela, só para ver se funciona o problema em questão. Se der tudo certo, a gente pode tratar isso ai com diretivas de compilação levando em consideração o Delphi Rio.

**Comment by viniciussanchez** [comment]
Boa tarde... algum retorno?
