### ISSUE TITLE
Bug em MakeUrl?

### ISSUE THREAD

**Issue by JohnnyWalkerJrFx** [viniciussanchez/RESTRequest4Delphi#207]
Exemplo de como reproduzir o erro na unit RESTRequest4D.Request.FPHTTPClient:
```
var
  Request: IRequest;
const
  lResource =  '/usuario/login';
begin
   Request := TRequest.New
                       .BaseURL('http://localhost:9095')
                       .Resource(lResource)
                       .ContentType('application/json');        
end;
```

Caro Vinícius, notei um bug na função MakeUrl() que quando a BaseUrl() não termina com '/' e tem a função Resource() conforme minha constante lResource de exemplo que se inicia com uma barra, vejo que não verifica o começo de FResource se essa variável se inicia com a '/' e isso gera o seguinte erro:

A função acrescenta a barra no final de BaseUrl(), pois no exemplo não a tem, mas depois por não verificar o começo(StartsWith()) de FResource  que começa com a '/' ele fica com duas barras na Url, dando problema.

o que ficaria assim, http://localhost:9095//usuario/login

Como não se verifica se a url é válida no final e nem gera erro, então dá esse problema com ela por mero desconhecimento de como funciona seu framework.

Espero que eu tenha conseguido deixar claro, apesar que ainda não me acostumei com o framework totalmente, mas continuo aprendendo.

Desde já, o meu muito obrigado por tudo que vocês fazem aí ajudando a comunidade pascal.

**Comment by viniciussanchez** [comment]
Ajustado no commit acima

**Comment by JohnnyWalkerJrFx** [comment]
Obrigado amigo...
