### ISSUE TITLE
Invalid File

### ISSUE THREAD

**Issue by VicenteSCV** [viniciussanchez/RESTRequest4Delphi#209]
estou tentando envia um arquivo e está retornando arquivo inválido.
    "status": 400,
    "error": "Bad Request",
    "message": [
        "Invalid File"

abaixo meu código, Estou fazendo algo errado?
![image](https://github.com/viniciussanchez/RESTRequest4Delphi/assets/128518827/37c9be09-dd12-44b5-b544-3136769d38a6)

Pelo Postaman está funcionando ok
![image](https://github.com/viniciussanchez/RESTRequest4Delphi/assets/128518827/ced98f22-9718-4a74-abdc-3c4bbfe7bc8d)

**Comment by viniciussanchez** [comment]
Bom dia... sim está fazendo errado. Você deve enviar form-data e não um json no body.
Na pasta samples tem exemplo de envio de form-data, da uma verificada por favor.
