### ISSUE TITLE
Implement async request

### ISSUE THREAD

**Issue by viniciussanchez** [viniciussanchez/RESTRequest4Delphi#21]

**Comment by allancmello** [comment]
Fala vinicius blz. 
Vc implementou async/await no RestRequest4Delphi? Isso?

Outra coisa. Dá uma melhorada na descrição de execução dos exemplos. Na parte  do server node, quem não manja de node e seus funcionamentos fica perdido.

Por exemplo, a execução do Boss é somente para o data-serialyzer, já para o server-node, é preciso acessar o diretorio do server-node e rodar o npm i para instalar as dependencias.
Para rodar o server npm run start.
Show de bola o RestRequest4Delphi, foi vc que desenvolveu?

Vlew, abraço

**Comment by viniciussanchez** [comment]
Oi @allancmello ,
Ainda não tive tempo de implementar o async, por isso criei essa issue aqui.
Obrigado pelas dicas....
Se estiver afim, pode ajudar a melhorar também fique a vontade... só mandar seu PR ;)
Se quiser implementar o async também... 
Projeto é aberto a comunidade...
Vlw

**Comment by dematecsistemas** [comment]
Ola Vinicius boa tarde, estou tentando fazer uma requisição via GET passando uma Chave pro Header e ta dando erro de autenticação, ja tentei de toda forma, veja o exemplo e não conecta, vc poderia me ajudar,

to passando essa 
url:  http://planilhacifal.ddns.net:5967/api/Arquivos/Buscar?Path=D:\Sistema\Cifal\Cheques\607800907.jpg

LResponse := TRequest.New.BaseURL(edtBaseURL.Text)
    .AddHeader('SystemKey','minhachave')
    .Accept(edtAccept.Text)
    .Get;

**Comment by viniciussanchez** [comment]
Tente colocar .AddHeader('header', value, [poDoNotEncode])

**Comment by dematecsistemas** [comment]
![image](https://user-images.githubusercontent.com/30877991/182947627-bd3cc553-d01b-47b4-90f5-fcb21f72106d.png)

A função não esta aceitando esse parâmetro.

**Comment by viniciussanchez** [comment]
@dematecsistemas se olhar o código fonte, verá que ela aceita, mas, tem que ser Delphi, tem que fazer o uso da classe REST.Types, e tem que usar o motor do RESTClient caso tenha alterado para o Indy ou NetHTTP. Lembrando que seu código fonte tem que estar atualizado
