### ISSUE TITLE
RESTRequest4D.Request.NetHTTP.pas(246): E2010 Incompatible types: 'string' and 'Boolean'

### ISSUE THREAD

**Issue by tibaros** [viniciussanchez/RESTRequest4Delphi#222]
I have a problem compiling the latest versions, I never had such problems before.

function TRequestNetHTTP.AddFile(const AFieldName: string; const AValue: TStream; const AFileName: string; const AContentType: string): IRequest;
{$IF COMPILERVERSION >= 33.0}
var
  LFileName: string;
{$ENDIF}
begin
  Result := Self;
  if not Assigned(AValue) then
    Exit;
  {$IF COMPILERVERSION >= 33.0}
    LFileName := Trim(AFileName);
    if (LFileName = EmptyStr) then
      LFileName := AFieldName;
    AValue.Position := 0;
  {$IF COMPILERVERSION >= 34.0} 
    FMultipartFormData.AddStream(AFieldName, AValue, True, LFileName, AContentType);  //----------> HERE ERROR!!!
  {$ELSE}
    FMultipartFormData.AddStream(AFieldName, AValue, LFileName, AContentType);
  {$ENDIF}
    FUseMultipartFormData := True;
  {$ENDIF}
end;

**Comment by nq2021** [comment]
I also encountered this error

**Comment by jcaique** [comment]
Whats the delphi version you are using?

**Comment by viniciussanchez** [comment]
Send us a pull request... please

**Comment by tibaros** [comment]
Was there a solution?
