### ISSUE TITLE
function AddParam :: pkGETorPOST vs pkQUERY

### ISSUE THREAD

**Issue by Rik69** [viniciussanchez/RESTRequest4Delphi#29]
Hi,

I use Delphi 10.4 (Sydney)
The following function give me a 404 error. Is there any reason why you force pkQUERY ?  It only works when I replace pkQUERY by pkGETorPOST.

unit RESTRequest4D.Request.Intf;

{$IF COMPILERVERSION < 33}
      function AddParam(const AName, AValue: string; const AKind: TRESTRequestParameterKind = TRESTRequestParameterKind.pkGETorPOST): IRequest;
    {$ELSE}
      function AddParam(const AName, AValue: string; const AKind: TRESTRequestParameterKind = TRESTRequestParameterKind.pkQUERY): IRequest;

**Comment by viniciussanchez** [comment]
The correct thing is to use pkQuery. But this was only implemented in Delphi RIO onwards. The 404 error needs to be analyzed in the context as a whole, as it should not give the error.

**Comment by viniciussanchez** [comment]
It's ok?

**Comment by Rik69** [comment]
In my case, I had to use GET or Post so, I used the native Delphi components.
