### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by viniciussanchez** [viniciussanchez/RESTRequest4Delphi#31]
Implement multipart/form-data

**Comment by anlopes123** [comment]
Olá gostaria de saber se essa Issue já foi implementada no componente ?

**Comment by viniciussanchez** [comment]
Não ainda não...

**Comment by acgnet** [comment]
Boa tarde! multpart/form-data já está implementada no componente?

**Comment by viniciussanchez** [comment]
Não

**Comment by viniciussanchez** [comment]
Escrevi este artigo para ajudar: https://vinicius-sanchez.medium.com/how-to-send-multipart-form-data-with-delphi-cb27d8d78c44

**Comment by acgnet** [comment]
Obrigado, ajudou muito!
Só mais uma dúvida, existe uma maneira de autenticar com o THTTPClient ?

No meu caso, eu preciso realizar uma autenticação utilizando um TokenBearer.

**Comment by viniciussanchez** [comment]
Só você adicionar o Header necessário... da sim

**Comment by acgnet** [comment]
Ok, muito obrigado pela ajuda!

**Comment by ms1sistemas** [comment]
Olá pessoal, foi integrado o multpart/form-data no componente ?

**Comment by viniciussanchez** [comment]
@ms1sistemas sim foi sim. Da uma olhada aqui:
https://github.com/viniciussanchez/RESTRequest4Delphi/pull/101
Na pasta samples também tem exemplos.
