### ISSUE TITLE
Implementar para uso em versões anteriores

### ISSUE THREAD

**Issue by wanderchavari** [viniciussanchez/RESTRequest4Delphi#33]
Olá @viniciussanchez, segue uma dica de um amigo para que possa ser utilizado em versões anteriores (no caso, usamos no Delphi XE7):

function TRequest.AddBody(const AContent: TStream; const AOwns: Boolean): IRequest;
begin
  Result := Self;
  {$IF COMPILERVERSION <= 29}
  FRESTRequest.AddBody(AContent, TRESTContentType.ctAPPLICATION_OCTET_STREAM);
  {$ELSE}
  FRESTRequest.Body.Add(AContent, TRESTContentType.ctAPPLICATION_OCTET_STREAM);
  {$ENDIF}

  if AOwns then
    AContent.Free;
end;

**Comment by juliosenha** [comment]
Bom dia Wander, acho que só faltou esse tratamento no AddBody para TStream, os demais já estão feitos.

**Comment by viniciussanchez** [comment]
Bom dia, vlw ;)
