### ISSUE TITLE
Cannot use RESTRequest4D - Unit not found.

### ISSUE THREAD

**Issue by L1NDS0N** [viniciussanchez/RESTRequest4Delphi#58]
Estou com um probleminha pra utilizar a lib, Acho que é só inexperiência minha com Delphi e packages mesmo 😣.
Acredito que essa questão seria mais conveniente nas issues do Boss, contudo, como se trata dessa lib, decidi perguntar aqui.

Possuo um projeto com um groupproj que possui vários packages, e preciso usar o  RESTRequest4D apenas em um package específico pois farei uma interação com uma api somente nesse package.
Quando eu instalo a lib com o boss, os diretórios de busca são inseridos no executável principal do sistema. Daí eu copio os caminhos e ponho no 'search path' do meu package '.bpl'. Mas quando faço a use do RESTRequest4D em uma das units desse package não consigo compilar o package.
Alguém pode me ajudar? Grato!

**Comment by viniciussanchez** [comment]
Acredito que se você der um boss init no diretório onde encontra o drp da sua bpl e depois dar um boss install nesse mesmo diretório, seu problema vai resolver...

**Comment by L1NDS0N** [comment]
Nada como um novo dia pra resolver problemas.
Deu tudo certo amigo! 
Pra quem vier após mim:
Removi todos os diretórios e .json relacionados ao Restrequest4D. Em seguida, criei um novo arquivo de versionamento direto no diretório do tal pacote que eu precisava, durante a configuração de inicialização do gerenciador boss, inseri manualmente o package name requerido na inicialização, já que o sugerido na configuração do boss diferia do nome do pacote .dpk. 
Foi isso que fiz, não sei se a explicação está coerente, mas funcionou pra mim.
