### ISSUE TITLE
Problema ao passar um GuiID com key.

### ISSUE THREAD

**Issue by charles-silva** [viniciussanchez/RESTRequest4Delphi#62]
**Não funciona.**
http://localhost:8080/datasnap/rest/tcategoria/categoria/{6A343FDD-AAFA-4531-91D1-FBA48EF232BF}
**funciona**
http://localhost:8080/datasnap/rest/tcategoria/categoria/1111

Se eu executar a primeira opção pelo Insomnia funciona normalmente.

**Comment by viniciussanchez** [comment]
O Insomnia faz o encode da URL, o RESTRequest4Delphi não faz isso automaticamente. Você que tem que passar o valor encodado para ele quando tiver necessidade como neste caso.
