### ISSUE TITLE
Problemas na Instalação

### ISSUE THREAD

**Issue by automacaosamos** [viniciussanchez/RESTRequest4Delphi#66]
Olá eu já tenho instalado no meu path o dmvcframework, mesmo assim preciso colocar na pasta dependências ?
mesmo colocando estou tendo esse erro:
[dcc32 Error] REST4D.pas(71): E2003 Undeclared identifier: 'IMVCAuthenticationHandler'
[dcc32 Error] REST4D.pas(89): E2086 Type 'IRESTSecurity' is not yet completely defined
[dcc32 Fatal Error] REST4D.Client.pas(6): F2063 Could not compile used unit 'REST4D.pas'

**Comment by viniciussanchez** [comment]
Bom dia... acho que esse problema não pertence a este projeto.
Não temos a unit REST4D. 
Acho que deve ser algo do DelphiMVCFramework e não do RESTRequest4Delphi

**Comment by automacaosamos** [comment]
Realmente, foi mal, obrigado já resolvi, e está funcionando perfeito, muito bom...
