### ISSUE TITLE
Content-Type enviando duas vezes a API

### ISSUE THREAD

**Issue by elpidiobaberge** [viniciussanchez/RESTRequest4Delphi#68]
Tenho uma API em java e ao realizar uma requisição percebi que era enviado duas vezes o Content-Type (application/json, application/json).

Na unit RESTRequest4D.Request.Client no create esta chamando o metodo Self.ContentType('application/json');

Eu comentei esse método e na minha requisição eu não alimentei o content type. Ficando assim.

  lRes := TRequest.New
                  .BaseURL('http://localhost:8084/SisGestao/api/login')
                  .AddBody(lJson)
                  .Post;

**Comment by Elpidio01** [comment]
eu fiz outro teste aqui. Eu enviei a requisição sem o Body nisso o content-type ficou o default application/x-www-form-urlencoded.
adicionando o body, reconheceu como application/json sem que eu precisasse alimentar.
