### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciussanchez/RESTRequest4Delphi#69]
Boa tarde, uso sua biblioteca de longa data até hoje tudo rodando normalmente porem me deparei com a necessidade de usar no windows 7, só que ai estou tendo problema não funciona. Tem ideia de como posso resolver? Grato

**Comment by viniciussanchez** [comment]
Qual o problema?

**Comment by alissonrodrigo** [comment]
não cheguei a testar com os componentes diretamente. uso sua biblioteca em todo o sistema

**Comment by viniciussanchez** [comment]
Conseguiu resolver o problema?

**Comment by alissonrodrigo** [comment]
Ha sim, na verdade o problema e com o win 7 em si, que não permitia requisição a https somente a http 
Muito obrigado
