### ISSUE TITLE
Contantes

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciussanchez/RESTRequest4Delphi#71]
Boa tarde, tudo bem? Poderia me ajudar, uso o RESTRequest4Delphi em todos meus projetos e gostaria de saber se teria como colocar alguns valores como constantes. 
Valores como Request.BasicAuthentication o praticamente não muda então todas as requisições tem o mesmo valor, então não faz sentido eu passar ele em todas as chamadas, gostaria de colocar alguns valores como constantes. 

Então todas as requisições já vão constar esses valores.
Grato

**Comment by viniciussanchez** [comment]
Boa tarde, atualmente não existe essa possibilidade

**Comment by viniciussanchez** [comment]
@alissonrodrigo, uma solução que eu julgaria ideal também é você nunca usar diretamente os componentes de terceiros. Por exemplo, o cenário ideal é sempre você ter uma classe antes entre o componente e a sua aplicação. Porque você não fica preso ao componente em questão. Se pensar por esse lado, daria para você colocar todos esses dados que pra você é padrão nessa classe. E ainda deixaria seu sistema ainda mais desacoplado da biblioteca....
