### ISSUE TITLE
TRequestIndy.Post incorrect execution

### ISSUE THREAD

**Issue by eduardomrj** [viniciussanchez/RESTRequest4Delphi#73]
Imagino que esteja errado o método abaixo
function TRequestIndy.Post: IResponse;
begin
  Result := FResponse;
  ExecuteRequest(mrGET);
end;

trocar para :

function TRequestIndy.Post: IResponse;
begin
  Result := FResponse;
  ExecuteRequest(mrPOST);
end;

**Comment by viniciussanchez** [comment]
Ajustado... obrigado
