### ISSUE TITLE
Show ? after export to TFDMemTable

### ISSUE THREAD

**Issue by kabiri** [viniciussanchez/RESTRequest4Delphi#74]
Hi 
This is my Code

```
  aRes:=TRequest.New.BaseURL(BaseURL)
        .Resource('Category')
        .BasicAuthentication('zig','zig')
        .DataSetAdapter(tblCategory)
        .Accept('Aplication/json')
        .Get;

```
aRes.Content value is :
[{"id":11,"pid":0,"categoryname":"\u011F\u00FC\u011E\u00DC\u0131I\u015Fi\u015E\u0130\u00F6\u00E7\u00D6\u00C7"}]

but frmData.tblCategory.FieldByName('CategoryName').AsWideString or frmData.tblCategory.FieldByName('CategoryName').AString show this '?ü?U?I?i???ç?C'

tblCategory is TFDMemTable

**Comment by viniciussanchez** [comment]
Hi, have you tried debugging to see where the problem is? I never had this problem...

**Comment by kabiri** [comment]
If I define the "CategoryName" field in the Fields Editor as a "widestring", it will display correctly.
But this happens when a field table is not defined.
I checked again that this error occurs again when I define a field in the Fields Editor as a "string".
Maybe the problem is the FD.

**Comment by viniciussanchez** [comment]
Yes, there is no way for me to identify what type of string it is. If you have inside double quotes, consider it as a string in the creation of fields.
