### ISSUE TITLE
SecureProtocols

### ISSUE THREAD

**Issue by brenomed** [viniciussanchez/RESTRequest4Delphi#76]
Olá a Todos!

Gostaria de saber como fica a chamada quando precisamos definir o protocolo, exemplo:
RestClient.SecureProtocols:=[THTTPSecureProtocol.TLS12];
Como fica usando o RESTRequest4Delphi?

Agradeço!

Abraço!

**Comment by viniciussanchez** [comment]
Boa tarde...
Ainda não implementei esse recurso. 
Se quiser implementar e contribuir com o projeto, fique a vontade...

**Comment by brenomed** [comment]
Boa tarde Vinicius!
Vou analisar aqui como implemento.
Obrigado pelo retorno.

**Comment by ZagnyV** [comment]
Boa tarde
I use Embarcadero® Delphi 10 Seattle. And RestClient-class in this version don't know about 'SecureProtocols' property. Could you fix this in the next update?
Muito Obrigado.

**Comment by viniciussanchez** [comment]
@ZagnyV yes... For now, download the latest released release

**Comment by KesleyBoletti** [comment]
Ola. tenho um projeto usando o RR4D no D11.1 e funciona tudo certo. Atualizei o Delphi para D11.2 e agora quando faço um post estou recebendo um erro. Vou anexar aqui.
Lembrando que o certifica é valido, e que esse mesmo projeto que estou falando aqui, esta em uso no Delphi 11.1. O problema que preciso subir uma atualização para a playstore então tive que atualizar para o D11.2

![Erro ao executar pot usando RR4D no D11 2](https://user-images.githubusercontent.com/37299977/204414787-0936efd8-3432-4b4e-95c5-fb6d95972afa.jpeg)
