### ISSUE TITLE
the request contains an entity body but no content-type header

### ISSUE THREAD

**Issue by rsoaresmga** [viniciussanchez/RESTRequest4Delphi#83]
Olá tudo bem?

Estou tentando enviar via post um JSON, segui o exemplo da wiki, porem estou tendo esse retorno, 

Ja tentei adicionar no header via AddHeader('Content-Type'... ja tentei usar o metodo ContentType('aplication/json') em ambos os casos a API me retorna essa mensagem, 

Existe forma de resolver?

Obrigado

**Comment by viniciussanchez** [comment]
Bom dia, precisava ver a doc da API.
Aparentemente está fazendo correto.

**Comment by rsoaresmga** [comment]
A doc da API nao ajuda muito tambem, tecnicamente o que tem e isso:

REQUEST:
Endpoint: /api/auth
Method: POST
Body:
JSON:
{
'email': 'SUBSTITUTA COM OS SEUS DADOS',
'key': 'SUBSTITUTA COM OS SEUS DADOS'
}
RESPONSE
JSON:
{
'Data': {
'Token': 'TokenRetornado'
},
'Message': null
}

**Comment by viniciussanchez** [comment]
Consegue consumir ela pelo postman?

**Comment by rsoaresmga** [comment]
Sim, pelo postman vai, e tambem pelo synapse.

Mas gostei demais da clareza de codigo desse componente

**Comment by rsoaresmga** [comment]
Uma coisa importante, a Lib indy em questao esta com aquele bug que precisa atualizar pra funcionar, porem eu acionei os metodos que chamam a REST ao inves da Indy

**Comment by viniciussanchez** [comment]
Complicado identificar o problema assim, mas basicamente seria isso aqui a sua requisição:
```pascal
TRequest.New.BaseURL('http://localhost:9000/api/auth')
  .AddBody(<<JSON do tipo TJSONObject>>)
  .Post;  
```

**Comment by rsoaresmga** [comment]
Sim, bem complicado, a doc da API e vaga, e pelo postman funcionando piora tudo rs, assim que eu acessar a maquina de deselvolvimento vou fazer uns testes pra ver se descubro a causa disso. Qualquer coisa volto aqui pra contar o motivo, muito obrigado.
