### ISSUE TITLE
Identifier idents no member "DisposeOf"

### ISSUE THREAD

**Issue by laprado** [viniciussanchez/RESTRequest4Delphi#90]
Olá,

grato pelo ótimo trabalho.

Estou tentando utilizar o RESTRequest4D com o Lazarus 2.2.0 e FPC 3.2.2 e estou com um problema na compilação do mesmo:
RESTRequest4D.Request.Indy.pas(112,18) Error: identifier idents no member "DisposeOf"
Linhas 132, 394, 419 e 436 também apresentam o mesmo problema.

Creio que seja por conta da linha:
{$IFDEF MSWINDOWS OR FPC}
Quando usado o $IFDEF o compilador ignora tudo depois da primeira condicional verificada, nesse caso ele não testa a condicional FPC. (fonte: [https://wiki.freepascal.org/Conditional_compilation](https://wiki.freepascal.org/Conditional_compilation)   -  tem um bloco de warning bem no meio dessa página explicando esse comportamento do $IFDEF)

Como alternativa tenho substituído essas linhas por
{$IF DEFINED(MSWINDOWS) OR DEFINED(FPC)}

grato.

**Comment by viniciussanchez** [comment]
Oi @laprado interessante, confesso que não usamos muito o lazarus por aqui, por isso não identifiquei o problema ainda. Mas muito obrigado por informar. Você quer enviar um pull request com as alterações? Ou quer que eu as implemente aqui?

**Comment by laprado** [comment]
Eu envio um pull request.

Obs: No Delphi o comportamento do $IFDEF é o mesmo, acho que acaba não surgindo problema mesmo quando não for MSWINDOWS porque o DisposeOf está sempre presente e acaba chamando o Free.

**Comment by viniciussanchez** [comment]
Tranquilo... fico no aguardo então. Obrigado
