### ISSUE TITLE
Exception? 

### ISSUE THREAD

**Issue by alissonrodrigo** [viniciussanchez/RESTRequest4Delphi#97]
Bom dia, tenho um servidor horse com uma url (flag) para o app consultar se o servidor está online. 
Quando faço uma requisição com o RestRequest nessa flag com o servidor offline o sistema 'trava' e não consigo tratar usando o bloco 

  try
    iResposta := TRequest.New.BaseURL(sServidor).Resource(sURL).Accept(aAccept).get;
    if iResposta.StatusCode = 200 then
      Result := True
    else
      Result := false;
  except
    on E: Exception do
    begin
      Result := false;
      TCrux.Log(E);
    end;
  end;

Algo que eu possa fazer para saber se o servidor está mesmo online? Grato

**Comment by viniciussanchez** [comment]
Somente fazendo um ping nele....
se está travando, a requisição deve estar esperando uma resposta. Verifique o timeout da sua requisição

**Comment by alissonrodrigo** [comment]
Quando eu passo o timeout ".Timeout(3000)" recebo a seguinte mensagem
Project GManutec.apk raised exception class ENetHTTPClientException with message 'java.net.ConnectException: Connection refused'.

quando não passo ele: 
Project GManutec.apk raised exception class ERESTException with message 'REST request failed: java.net.SocketTimeoutException: connect timed out'.

Lembrando que o servidor está desligado. Já que minha intenção e apenar verificar se está online.

**Comment by viniciussanchez** [comment]
Certo, mas não entendi o problema, ambas as mensagens estão corretas...
